language: ruby
bundler_args: "--without development"
addons:
  code_climate:
    repo_token:
      secure: CQX/SC+6qqpKgYtqe/MxY7yZyx9tSEgNuvWzgBhg71OHoCUUV0mnZdDmsXkX2QgkEnWGpsTsPyyqRBBvZaR+SbqdQVwMFiqmo1Ij4nsMJuwQKLADUkNCV0WhWW/M1fqRaRR/r85CD6TUezot943aaDzNvy7oeVspiERIpuqiuNU=
notifications:
  slack:
    rooms:
      secure: maWpNOd6DyV+bf1BTHMvRYtAWgnZqrCz7P6Uu9OnxVz9AKgednGV5ZLuJqVtm8l38corAzUC58b4zdtpelD8ExDWZc3auv7I/kInLOM+oDTevONaIlW3GGfTzMB9yyLka5vV/m769e35J3rLsHJr1F/bFsGQGLxPFBsACLAxbXs=
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- gem install bundler -v 1.10.6
before_script:
- bundle exec rake db:setup
after_success:
- "./script/deploy-staging.sh"
